# Generated by Django 4.2.4 on 2023-08-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="joined_date",
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="home",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
